# SAM デプロイ設定

version = 0.1

[default.global.parameters]
stack_name = "proworks-recommend-batch"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = true
s3_prefix = "proworks-recommend-batch"

[dev.deploy.parameters]
stack_name = "proworks-recommend-batch-dev"
region = "ap-northeast-1"
parameter_overrides = [
    "Environment=dev"
]

[prod.deploy.parameters]
stack_name = "proworks-recommend-batch-prod"
region = "ap-northeast-1"
parameter_overrides = [
    "Environment=prod"
]
